---
- name: Run Setup To Lookup Facts
  setup: {}

- name: Make Sure ansible_pull was applied on this system
  assert:
    that: ansible_local.pull is defined
    fail_msg: It doesnt look like ansible pull has been configured on this system.

- name: Parse SCM Repo Url Parts
  set_fact:
    _scm_url_parts:
      user: "{{ pull_job_repo_url | regex_search('^(\\w*)@.*', '\\1') | first }}"
      host: "{{ pull_job_repo_url | regex_search('^.*@([\\w.]*):.*', '\\1') | first }}"
      project: "{{ pull_job_repo_url | regex_search('.*:.*/(.*)\\.git', '\\1') | first }}"

- name: Make Sure Directories are Present
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ pull_job.full_working_dir }}"
    - "{{ pull_job.full_log_dir }}"

- name: Template Run Script
  template:
    src: run_pull.sh.j2
    dest: "{{ pull_job.full_working_dir }}/run_pull.sh"
    mode: '0700'

- name: Create Cron Definition
  set_fact:
    _cron_def:
      name: "{{ pull_job_name }}"
      job: "{{ pull_job.full_working_dir }}/run_pull.sh > {{ pull_job.full_log_dir }}/run_pull.log-`date +\\%Y\\%m\\%d`.log"

- name: Template SSH Config
  template:
    src: sshd_config.j2
    dest: "{{ pull_job.full_working_dir }}/sshd_config"

- name: Create Job
  cron: "{{ _cron_def | combine(pull_job_schedule) }}"
