---
- name: Include Ansipull Bootstrap
  include_tasks: "{{ role_path }}/tasks/bootstrap_pull.yml"

- name: Make Sure ansible_pull was applied on this system
  assert:
    that: ansible_local.pull is defined
    fail_msg: It doesnt look like ansible pull has been configured on this system.

- name: Parse SCM Repo Url Parts
  set_fact:
    _scm_url_parts:
      user: "{{ pull_job_repo_url | regex_search('^(\\w*)@.*', '\\1') | first }}"
      host: "{{ pull_job_repo_url | regex_search('^.*@([\\w.]*):.*', '\\1') | first }}"
      project: "{{ pull_job_repo_url | regex_search('.*:.*/(.*)\\.git', '\\1') | first }}"

- name: Make Sure Directories are Present
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ pull_job.project_dir }}"
    - "{{ pull_job.job_dir }}"
    - "{{ pull_job.log_dir }}"

- name: Template Run Script
  template:
    src: run_pull.sh.j2
    dest: "{{ pull_job.job_dir }}/run_pull.sh"
    mode: '0700'

- name: Copy Repo RSA File Over
  block:
    - name: Update repo RSA file from local
      copy:
        src: "{{ pull_job_place_rsa_file }}"
        dest: "{{ pull_job.project_dir }}/repo_rsa_key"
        mode: '0600'
        remote_src: true
  rescue:
    - name: Copy repo RSA file from ansible host
      copy:
        src: "{{ pull_job_place_rsa_file }}"
        dest: "{{ pull_job.project_dir }}/repo_rsa_key"
        mode: '0600'
        remote_src: false
  when: pull_job_place_rsa_file

- name: Create Cron Definition
  set_fact:
    _cron_def:
      name: "{{ pull_job.fq_name }}"
      job: "{{ pull_job.job_dir }}/run_pull.sh > {{ pull_job.log_dir }}/run_pull.log-`date +\\%Y\\%m\\%d`.log"

- name: Create Job
  cron: "{{ _cron_def | combine(pull_job_schedule) }}"

- name: Update Job Facts
  include_tasks: "{{ role_path }}/tasks/update_job_facts.yml"

- name: Run Job Now
  shell: "{{ pull_job.job_dir }}/run_pull.sh > {{ pull_job.log_dir }}/run_pull.log-`date +\\%Y\\%m\\%d`.log"
  when: pull_job.run_now
