---
- name: Create Fact Directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/ansible
    - /etc/ansible/facts.d

- name: Template Fact File
  template:
    src: ansipull_jobs.fact.j2
    dest: /etc/ansible/facts.d/ansipull_jobs.fact

- name: Refresh Facts
  setup:
    filter: "ansible_local"
